apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nodede
  janus-idp.io/tekton: nodede
  backstage.io/kubernetes-id: nodede
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodede
resources:
- deployment.yaml
- route.yaml
- service.yaml
