apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodede
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/kkanova0/node:349b6697277ce41ab4e62205bbc0cb723ea90d6e@sha256:91fe7538b63835e76001ae3c0928a84634c6879bec140a718702fa86a236a245
          name: container-image
